packages:
  - '.'
allowBuilds:
  core-js: true
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - react-f0rm
  - react-toolroom
  - haze-ui
  - fetch-fun
  - react-use-control
  - '@native-router/*'
  - '@for-fun/*'
