allowBuilds:
  core-js: true
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - react-f0rm
  - react-toolroom
  - haze-ui
  - '@native-router/core'
  - '@native-router/react'
  - '@for-fun/event-emitter'
