/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Existing user login
         * @description Login for existing user
         */
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Register a new user */
        post: operations["CreateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Gets the currently logged-in user
         */
        get: operations["GetCurrentUser"];
        /**
         * Update current user
         * @description Updated user information for current user
         */
        put: operations["UpdateCurrentUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a profile
         * @description Get a profile of a user of the system. Auth is optional
         */
        get: operations["GetProfileByUsername"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{username}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Follow a user
         * @description Follow a user by username
         */
        post: operations["FollowUserByUsername"];
        /**
         * Unfollow a user
         * @description Unfollow a user by username
         */
        delete: operations["UnfollowUserByUsername"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recent articles from users you follow
         * @description Get most recent articles from users you follow. Use query parameters to limit. Auth is required
         */
        get: operations["GetArticlesFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recent articles globally
         * @description Get most recent articles globally. Use query parameters to filter results. Auth is optional
         */
        get: operations["GetArticles"];
        put?: never;
        /**
         * Create an article
         * @description Create an article. Auth is required
         */
        post: operations["CreateArticle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an article
         * @description Get an article. Auth not required
         */
        get: operations["GetArticle"];
        /**
         * Update an article
         * @description Update an article. Auth is required
         */
        put: operations["UpdateArticle"];
        post?: never;
        /**
         * Delete an article
         * @description Delete an article. Auth is required
         */
        delete: operations["DeleteArticle"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{slug}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get comments for an article
         * @description Get the comments for an article. Auth is optional
         */
        get: operations["GetArticleComments"];
        put?: never;
        /**
         * Create a comment for an article
         * @description Create a comment for an article. Auth is required
         */
        post: operations["CreateArticleComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{slug}/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a comment for an article
         * @description Delete a comment for an article. Auth is required
         */
        delete: operations["DeleteArticleComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{slug}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Favorite an article
         * @description Favorite an article. Auth is required
         */
        post: operations["CreateArticleFavorite"];
        /**
         * Unfavorite an article
         * @description Unfavorite an article. Auth is required
         */
        delete: operations["DeleteArticleFavorite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get tags
         * @description Get tags. Auth not required
         */
        get: operations["GetTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginUser: {
            email: string;
            /** Format: password */
            password: string;
        };
        NewUser: {
            username: string;
            email: string;
            /** Format: password */
            password: string;
        };
        User: {
            email: string;
            token: string;
            username: string;
            bio: string | null;
            image: string | null;
        };
        UpdateUser: {
            email?: string;
            password?: string;
            username?: string;
            bio?: string | null;
            image?: string | null;
        };
        Profile: {
            username: string;
            bio: string | null;
            image: string | null;
            following: boolean;
        };
        Article: {
            slug: string;
            title: string;
            description: string;
            body: string;
            tagList: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            favorited: boolean;
            favoritesCount: number;
            author: components["schemas"]["Profile"];
        };
        NewArticle: {
            title: string;
            description: string;
            body: string;
            tagList?: string[];
        };
        UpdateArticle: {
            title?: string;
            description?: string;
            body?: string;
            tagList?: string[];
        };
        Comment: {
            id: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            body: string;
            author: components["schemas"]["Profile"];
        };
        NewComment: {
            body: string;
        };
        GenericErrorModel: {
            errors: {
                [key: string]: string[];
            };
        };
    };
    responses: {
        /** @description Tags */
        TagsResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    tags: string[];
                };
            };
        };
        /** @description Single comment */
        SingleCommentResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    comment: components["schemas"]["Comment"];
                };
            };
        };
        /** @description Multiple comments */
        MultipleCommentsResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    comments: components["schemas"]["Comment"][];
                };
            };
        };
        /** @description Single article */
        SingleArticleResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    article: components["schemas"]["Article"];
                };
            };
        };
        /** @description Multiple articles */
        MultipleArticlesResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    articles: {
                        slug: string;
                        title: string;
                        description: string;
                        tagList: string[];
                        /** Format: date-time */
                        createdAt: string;
                        /** Format: date-time */
                        updatedAt: string;
                        favorited: boolean;
                        favoritesCount: number;
                        author: components["schemas"]["Profile"];
                    }[];
                    articlesCount: number;
                };
            };
        };
        /** @description Profile */
        ProfileResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    profile: components["schemas"]["Profile"];
                };
            };
        };
        /** @description User */
        UserResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    user: components["schemas"]["User"];
                };
            };
        };
        /** @description No content */
        EmptyOkResponse: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "errors": {
                 *         "token": [
                 *           "is missing"
                 *         ]
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["GenericErrorModel"];
            };
        };
        /** @description Conflict - resource already exists */
        ConflictError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "errors": {
                 *         "username": [
                 *           "has already been taken"
                 *         ]
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["GenericErrorModel"];
            };
        };
        /** @description Forbidden. The error key identifies the resource type (article, comment, etc.) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "errors": {
                 *         "resource": [
                 *           "forbidden"
                 *         ]
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["GenericErrorModel"];
            };
        };
        /** @description Not Found. The error key identifies the resource type (article, profile, comment, etc.) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "errors": {
                 *         "resource": [
                 *           "not found"
                 *         ]
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["GenericErrorModel"];
            };
        };
        /** @description Unexpected error */
        GenericError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "errors": {
                 *         "title": [
                 *           "can't be blank"
                 *         ]
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["GenericErrorModel"];
            };
        };
    };
    parameters: {
        /** @description The number of items to skip before starting to collect the result set. */
        offsetParam: number;
        /** @description The numbers of items to return. */
        limitParam: number;
    };
    requestBodies: {
        /** @description Credentials to use */
        LoginUserRequest: {
            content: {
                "application/json": {
                    user: components["schemas"]["LoginUser"];
                };
            };
        };
        /** @description Details of the new user to register */
        NewUserRequest: {
            content: {
                "application/json": {
                    user: components["schemas"]["NewUser"];
                };
            };
        };
        /** @description User details to update. At least **one** field is required. */
        UpdateUserRequest: {
            content: {
                "application/json": {
                    user: components["schemas"]["UpdateUser"];
                };
            };
        };
        /** @description Article to create */
        NewArticleRequest: {
            content: {
                "application/json": {
                    article: components["schemas"]["NewArticle"];
                };
            };
        };
        /** @description Article to update */
        UpdateArticleRequest: {
            content: {
                "application/json": {
                    article: components["schemas"]["UpdateArticle"];
                };
            };
        };
        /** @description Comment you want to create */
        NewCommentRequest: {
            content: {
                "application/json": {
                    comment: components["schemas"]["NewComment"];
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["LoginUserRequest"];
        responses: {
            200: components["responses"]["UserResponse"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["GenericError"];
        };
    };
    CreateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["NewUserRequest"];
        responses: {
            201: components["responses"]["UserResponse"];
            409: components["responses"]["ConflictError"];
            422: components["responses"]["GenericError"];
        };
    };
    GetCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["UserResponse"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["GenericError"];
        };
    };
    UpdateCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UpdateUserRequest"];
        responses: {
            200: components["responses"]["UserResponse"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["GenericError"];
        };
    };
    GetProfileByUsername: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Username of the profile to get */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ProfileResponse"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["GenericError"];
        };
    };
    FollowUserByUsername: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Username of the profile you want to follow */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ProfileResponse"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["GenericError"];
        };
    };
    UnfollowUserByUsername: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Username of the profile you want to unfollow */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ProfileResponse"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["GenericError"];
        };
    };
    GetArticlesFeed: {
        parameters: {
            query?: {
                /** @description The number of items to skip before starting to collect the result set. */
                offset?: components["parameters"]["offsetParam"];
                /** @description The numbers of items to return. */
                limit?: components["parameters"]["limitParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["MultipleArticlesResponse"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["GenericError"];
        };
    };
    GetArticles: {
        parameters: {
            query?: {
                /** @description Filter by tag */
                tag?: string;
                /** @description Filter by author (username) */
                author?: string;
                /** @description Filter by favorites of a user (username) */
                favorited?: string;
                /** @description The number of items to skip before starting to collect the result set. */
                offset?: components["parameters"]["offsetParam"];
                /** @description The numbers of items to return. */
                limit?: components["parameters"]["limitParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["MultipleArticlesResponse"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["GenericError"];
        };
    };
    CreateArticle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["NewArticleRequest"];
        responses: {
            201: components["responses"]["SingleArticleResponse"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["ConflictError"];
            422: components["responses"]["GenericError"];
        };
    };
    GetArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug of the article to get */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["SingleArticleResponse"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["GenericError"];
        };
    };
    UpdateArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug of the article to update */
                slug: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UpdateArticleRequest"];
        responses: {
            200: components["responses"]["SingleArticleResponse"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["GenericError"];
        };
    };
    DeleteArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug of the article to delete */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["EmptyOkResponse"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["GenericError"];
        };
    };
    GetArticleComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug of the article that you want to get comments for */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["MultipleCommentsResponse"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["GenericError"];
        };
    };
    CreateArticleComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug of the article that you want to create a comment for */
                slug: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["NewCommentRequest"];
        responses: {
            201: components["responses"]["SingleCommentResponse"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["GenericError"];
        };
    };
    DeleteArticleComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug of the article that you want to delete a comment for */
                slug: string;
                /** @description ID of the comment you want to delete */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["EmptyOkResponse"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["GenericError"];
        };
    };
    CreateArticleFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug of the article that you want to favorite */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["SingleArticleResponse"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["GenericError"];
        };
    };
    DeleteArticleFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug of the article that you want to unfavorite */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["SingleArticleResponse"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["GenericError"];
        };
    };
    GetTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TagsResponse"];
            422: components["responses"]["GenericError"];
        };
    };
}
